### ISSUE TITLE
Pulling the latest Version of the demo-deployer give me an Error

### ISSUE THREAD

**Issue by DarrenDoyle** [newrelic/demo-catalog#30]
[NOTE]: # ( ^^^^ )

## Description

Receving the following exception. 

## Steps to Reproduce

```
C02ZPGV6MD6P:demo-deployer ddoyle$ docker build -t deployer .

C02ZPGV6MD6P:demo-deployer ddoyle$ docker build -t deployer .
Sending build context to Docker daemon  22.37MB
Step 1/24 : FROM ubuntu:18.04
 ---> 5a214d77f5d7
Step 2/24 : RUN apt-get clean all
 ---> Using cache
 ---> 67e154f14ca7
Step 3/24 : RUN apt-get update
 ---> Using cache
 ---> 958b99c4750c
Step 4/24 : RUN apt-get install ruby-full -y
 ---> Using cache
 ---> 2fb04ec90a5d
Step 5/24 : RUN gem install bundler -v 1.17.3
 ---> Using cache
 ---> 61f8ccc66ae3
Step 6/24 : RUN apt-get install -y python3-pip python3-dev   && cd /usr/local/bin   && ln -s /usr/bin/python3 python   && pip3 install --upgrade pip
 ---> Using cache
 ---> dcd5283e4b15
Step 7/24 : RUN apt-get update
 ---> Using cache
 ---> b752e749eb83
Step 8/24 : RUN apt-get install git -y
 ---> Using cache
 ---> 2b9ad15122f0
Step 9/24 : RUN apt-get install rsync -y
 ---> Using cache
 ---> 86bf637f62f4
Step 10/24 : RUN apt-get update
 ---> Using cache
 ---> a96eae1532ca
Step 11/24 : RUN apt-get install software-properties-common curl -y
 ---> Using cache
 ---> be77dd821cad
Step 12/24 : RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
 ---> Using cache
 ---> d889d41d30dc
Step 13/24 : RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com bionic main"
 ---> Using cache
 ---> 3e9f389be648
Step 14/24 : RUN apt-get update && apt-get install terraform -y
 ---> Using cache
 ---> 2743d5aa6005
Step 15/24 : RUN mkdir /mnt/deployer
 ---> Using cache
 ---> b62ff93c8099
Step 16/24 : WORKDIR /mnt/deployer
 ---> Using cache
 ---> cf641655a88d
Step 17/24 : COPY Gemfile Gemfile.lock /mnt/deployer/
 ---> Using cache
 ---> d380e2ac7d57
Step 18/24 : RUN bundle install --clean --force
 ---> Using cache
 ---> e02e2ecccbd5
Step 19/24 : COPY requirements.python.txt requirements.ansible.yml /mnt/deployer/
 ---> Using cache
 ---> 1679d6fc014e
Step 20/24 : RUN python3 -m pip install -r requirements.python.txt
 ---> Running in f01e4baa6c07
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from -r requirements.python.txt (line 2)) (39.0.1)
Collecting ansible==2.9.9
  Downloading ansible-2.9.9.tar.gz (14.2 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 339, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    version=version,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 287, in __init__
    version=version,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 528, in _prepare_linked_requirement
    link, req.source_dir, self._download, self.download_dir, hashes
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 223, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/unpacking.py", line 247, in unpack_file
    untar_file(filename, location)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/unpacking.py", line 218, in untar_file
    with open(path, "wb") as destfp:
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 112: ordinal not in range(128)
The command '/bin/sh -c python3 -m pip install -r requirements.python.txt' returned a non-zero code: 2
```
## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

Not sure what the issue is, any thoughts?

**Comment by aswanson-nr** [comment]
Hey @DarrenDoyle! This is an issue we have run into, but haven't been able to prioritize time to fix. It was also reported over here https://github.com/newrelic/demo-deployer/issues/96.
The current workaround is to pull the image from [registry](https://github.com/newrelic/demo-deployer/pkgs/container/deployer), instead of building it locally!
