### ISSUE TITLE
issue deploying demos from catalog to AWS failing with VPC not found error

### ISSUE THREAD

**Issue by andresmmujica** [newrelic/demo-catalog#32]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # Deployment fails at the very begining showing a deprecation warning for ec2_vpc_net_facts renamed to ec2_vpc_net_info
```

Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/cloud/amazon/_ec2_vpc_net_facts.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-550fmpgif__/tmpc0z3145b TO /root/.ansible/tmp/ansible-tmp-1643076947.1225753-602-184807364474815/AnsiballZ__ec2_vpc_net_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1643076947.1225753-602-184807364474815/ /root/.ansible/tmp/ansible-tmp-1643076947.1225753-602-184807364474815/AnsiballZ__ec2_vpc_net_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1643076947.1225753-602-184807364474815/AnsiballZ__ec2_vpc_net_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1643076947.1225753-602-184807364474815/ > /dev/null 2>&1 && sleep 0'
[DEPRECATION WARNING]: The 'ec2_vpc_net_facts' module has been renamed to 'ec2_vpc_net_info'. This feature will be removed in version
 2.13. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost] => {
 
```

```

[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # (configure AWS credentials per instructions and deploy 

## Expected Behavior

[NOTE]: # telcolite deployed in AWS

## Relevant Logs / Console output


       },
        "vpc_id": "vpc-0e1dbcd3269070569"
    },
    "skip_reason": "Conditional result was False"
}

TASK [fail] **************************************************************************************************************************
task path: /tmp/dd-telcolite/reportinghost/vpc.yml:16
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": "VPC Subnet not found"
}

PLAY RECAP ***************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

[ERROR]
/mnt/deployer/src/provision/provisioner.rb:38:in `execute'
/mnt/deployer/src/provision/orchestrator.rb:38:in `block in execute'
/mnt/deployer/src/provision/orchestrator.rb:36:in `each'
/mnt/deployer/src/provision/orchestrator.rb:36:in `execute'
/mnt/deployer/src/orchestrator.rb:27:in `execute'
main.rb:11:in `<main>'
[dd@andres-55g3 configs]$ 
 
```
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

Linux

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by andresmmujica** [comment]
Found the issue, not related to the deployer but with AWS Account.

It turns out that who knows when or how, the Default VPC was deleted and there's no way to create a new one, gladly it is a lab account so not a big deal.
